-- اجرا در Supabase > SQL Editor
create table if not exists public.tanks (
  id bigint generated by default as identity primary key,
  name text not null unique,
  capacity_l numeric(12,2) not null check (capacity_l > 0),
  stock_l numeric(12,2) not null default 0 check (stock_l >= 0 and stock_l <= capacity_l)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  tank_id bigint not null references public.tanks(id),
  tank_name text not null,
  type text not null check (type in ('in','out')),
  amount_l numeric(12,2) not null check (amount_l > 0),
  operator text,
  equipment text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

insert into public.tanks(name,capacity_l,stock_l) values
('برش ۱۱',2000,2000),('آب صابون',2000,2000),('روغن هیدرولیک',1000,1000),('روغن روانکاری',1000,1000)
on conflict(name) do nothing;

alter table public.tanks enable row level security;
alter table public.transactions enable row level security;

create policy "authenticated can read tanks" on public.tanks for select to authenticated using (true);
create policy "authenticated can read transactions" on public.transactions for select to authenticated using (true);

create or replace function public.record_stock_transaction(
  p_tank_id bigint, p_type text, p_amount_l numeric,
  p_operator text default null, p_equipment text default null
) returns void language plpgsql security definer set search_path=public
as $$
declare t public.tanks%rowtype;
begin
  if auth.uid() is null then raise exception 'unauthorized'; end if;
  select * into t from public.tanks where id=p_tank_id for update;
  if not found then raise exception 'tank not found'; end if;
  if p_amount_l <= 0 then raise exception 'amount must be positive'; end if;
  if p_type='in' then
    if t.stock_l+p_amount_l>t.capacity_l then raise exception 'capacity exceeded'; end if;
    update public.tanks set stock_l=stock_l+p_amount_l where id=p_tank_id;
  elsif p_type='out' then
    if t.stock_l<p_amount_l then raise exception 'insufficient stock'; end if;
    update public.tanks set stock_l=stock_l-p_amount_l where id=p_tank_id;
  else raise exception 'invalid transaction type'; end if;
  insert into public.transactions(tank_id,tank_name,type,amount_l,operator,equipment,created_by)
  values(t.id,t.name,p_type,p_amount_l,p_operator,p_equipment,auth.uid());
end $$;

grant execute on function public.record_stock_transaction(bigint,text,numeric,text,text) to authenticated;
